name: phpapp deployment

on:
 push:
   branches:
   - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
     - name: checkout
       uses: actions/checkout@v1
       
    
     - name: deploy app to s3 bucket
       run: aws s3 sync . s3//phpappbucket --delete

