name: phpapp deployment

on:
 push:
   branches:
   - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
     - name: checkout
       uses: actions/checkout@v1
       
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-secret-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-2

     - name: deploy app to s3 bucket
       run: aws s3 sync . s3//phpappbucket --delete

